### PR TITLE
Minor: added ignore options, included settings merge and clean

### PR DESCRIPTION
**Pull request by Izzette**
### Minor: added ignore options, included settings merge and clean
* Added options to not evaluate header, content, or tags of posts.
  * The keys of the options are ignore_header, ignore_body, and ignore_tags, respectively.

  * Their defaults are all false; as such, the operation of the extension stays the same immediately after update.
  * Settings are marked up like so:
screenshot from 2015-04-12 01-01-27

  * I felt that they check boxes were least obscured and out of place when placed at the top of the settingsDiv, just after the header.

* On load, settings merge with and are cleaned based on the current default settings.
  * These changes are implemented through src/lib/main.js/checkSettings(parsedSettings).

  * Key-value pairs missing from the loaded settings are added with their default values

  * Key-value pairs not present in default settings are removed

  * Settings are ordered according to the default settings

  * If changes are made, they are saved to localstorage

* Tested on Chromium, Google Chrome, and Firefox
  * Settings from 82c0648c4e48a5b3b6f6e8ea82519ef9e5ec4da9 of the master branch were preserved.

  * During testing these changes, no errors or warnings occurred.

  * The functionality of the old features would be preserved.

  * The functionality of the new features appears to be consistent.

* Not tested on Safari or on a platform other than Linux
  * However, I do not foresee any introduced compatibility problems.

It got messy, I needed a fresh fork, single commit, and new pull request.  Thanks for being patient with me.

### CODE REVIEW

**Comment by Izzette** [comment]
Do you want this settings discovery code, but not the ignore options?  Considering ac0e0f21a0a8b1a8d9d5c344b732b0662e8a972d

**Comment by bjornstar** [comment]
Actually, the other way around. I'll take your ignore options, but I don't want to change the users settings for them.

**Comment by Izzette** [comment]
Okay, I'll fix that up.  Undefined evaluates false anyways, so it works out as long as new options default to false.

**Comment by Izzette** [comment]
Opened v0.4.22 #26

**Pull request closed without merging**
