### PR TITLE
v0.4.22

### PR DESCRIPTION
**Pull request by Izzette**
* Added options to ignore header, content, and/or tags of posts

Look good?

### CODE REVIEW

**Comment by bjornstar** [comment]
Sweet! Thank you so much for your patience.

**Comment by Izzette** [comment]
Your welcome.

I would however like to point out (in a totally non-snarky way) that my other change doesn't actually change anybodies settings at all.  It *only* syncs options that have been changed with the default, and leaves the other ones alone.  The only time it could change the behavior of Tumblr-Savior, is if the new options defaults change the behavior.  If any new options that change the behavior of Tumblr-Savior when they are false, then they would change the default behavior without merging them with the defaults.

**Comment by bjornstar** [comment]
Yep, I get it. However, I don't want people to be surprised by a new option that I want as the default. Existing users opt-in to new features; new users opt-out.

**Comment by Izzette** [comment]
Yeah, that makes sense.

**Pull request merged**
